# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a10e044f285dfb6b81beaf971e050597a33b46c11a2431fea93b726f31e2a724122313891bd24f89c128c602c12b8912e82aee76d8dfbea43babdeeb3c19ca

test:
  secret_key_base: e03173b2d9a45c72c4b32c9a436703ba8e369256ad8087b1d7f4264f00fb0fbf28024e296bd58c7e91e455b44c055be2ab78df31f3dfe875f6beff749dd173b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
